language: node_js
node_js: node
script:
- npm run build
after_success:
- '[ "$TRAVIS_SECURE_ENV_VARS" = "true" ] && export NODE_ENV=production && npm run
  publish-release'
env:
  global:
  # S3_SECRET
  - secure: zRKSVMQulBYLPiC1n2MPGff7X4QPUOKgasKXniCvYl2nf6KNAA34jjTK2tkBYEqi4o6LpuMXzJL07E9oy9FoGFpPuspVLjVWKEvJ/MlSPMrlD7bm37GKjHHhp0M8/eb0nczbw8j4Um1Vt+ouMtzUyzUaNi4CiveLQXqTq9CJQYcAEyCXKaJgHAbwVJfC/dQ3P78EgD967g8bvVsV0AijM/NnPZ3EgwIdcRkJduZuBd/EkO3h8vhpJSNTV/omeeurf6aU5c3WH8AlyiUJbinJ0iswyehx17oXeEmQ/4rDQxzpEcCcNvusUz8xu5finXBOxJmlK2nrxO9G7+jYYAXJ0yfaAcGav6s1Lhl2H64cWZuN0+hpG6n+44cZ8P2/qB9YIfdC/m3wDxiNWsrhw6qJbX7I1JGUK+uQOtu1ypGkpfZqM3WV5G1QN06Sok94KdVsyJa++bvlmz9RV+MvZdHL9fzFg03HEEgZFj2I0Wzw4GB+v38caD5Txulq/B+lk+JbSPCIqVWgSmEeM9AYOP48xjd3Yi/MS4g4clRxB/z7VdcOKUTDpyvd0P77OL2DNxcb2B00DOZ/7kVW0fyWgOsU0e+PUXeSMcmfQlZJ2Nzh0WtvKwwgIW/skUk/buJDtecxzkl9ha2Q5vfkz2tM9KrmQB6T5doyQTrws8oDvBD2l/Y=
  # GITHUB_TOKEN
  - secure: lesZkFj10QSmQXLk13R9I/wQOLhW4AQ+OkEACW6N5GAXK7OYiVZ69IyIWO7cxKqtax+AqHChMN2JFf6ZGhVXOYxX6Q6XIAfBltCd31vclMx/tvcD10UFGmVOBN4EO42XB88gn22rux6uAO+P4IfJDO1X1Ul+KWTpyA7K+d31WpOBiwXKA4i3jLpKyunsjdVYV0utrXbS55GPqLNpB/gY2QY/xv/SaimjOpQcREONHluOXeVx9fpwu3KMWtTKH8jJOdepSyn0EyIQCUuhQPj+KEkCK+sQBXV5mdvlp9G4BHBJRJH9HMMscaHYpSDUdxUnN6zTaji5DDvK2iyGY5kAYjY13V7TD5PXFTgoImL4hilnK4BNPA9kc0QLXLyl+vfvScsqkF+jTQ0i7n5Sz8HOnXpHkD0lmvBcvhCY+QkfD2VZCgRyBj2fWplsv+ZwhVrAagNQaGtRg8bEcT1Xr0VNp9BlXYlhH2oXLLx+yo4jAQLhLHA8Y5nECWdCVXcTOIdLDjZGz6Y5KDdfqhXfhBJQGY2bbN0UXw9cfZ35Yrk6gqy1ExmIPNy1QJ49JEabuwAo92iQ3Gb7aYpTc3D/6LMqvovyW8wspdiqQiUn3DnE5hM1sLHE7UYaL9vOSwmnlelqdfI280BsKqLqQZmIPASfEJah3TJkoAdYJQtkRpCGiog=
